; RUN: llvm-mc -triple tlcs900 -show-encoding < %s \
; RUN:     | FileCheck -check-prefixes=CHECK,CHECK-ENC %s
; RUN: llvm-mc -triple tlcs900 -filetype=obj %s \
; RUN:     | llvm-objdump -d - | FileCheck --check-prefix=CHECK-INST %s
;
; MEMORY-PREFIX SUB-OPCODES THE DISASSEMBLER COULD NOT READ.
;
; The 0x80/0x90/0xA0 (source: byte/word/long) and 0xB0/0xB8 (destination)
; memory prefixes share sub-opcode tables whose ALU and bit-operation halves
; had no decode.  llvm-mc encoded every form below; llvm-objdump answered
; "invalid instruction encoding" -- or, worse, read a DESTINATION-table
; sub-opcode through the SOURCE table's ALU rows and printed a different
; instruction that re-assembled to different bytes (`b3 c8` is "bit 0,(xhl)"
; and came back as "and (xhl), xwa", which encodes to `a3 c8`).
;
; The leading byte is not the unit of the gap: `9f 06 81` was refused while
; `9f 08 23` read fine, and both start 0x9f.  The families below are named by
; (prefix table, sub-opcode), which is what the decoder dispatches on.
;
; PROVENANCE.  Every byte sequence is read out of a committed KN5000 dump at
; the offset named beside it, and is a statement the disassembly tree's own
; source already assembles to those bytes.  MAME unidasm's rendering is quoted
; as an independent decode.  kn5000-roms-disasm's
; scripts/analysis/mem_prefix_test_sites.py --check re-reads every offset from
; the dumps, re-assembles every asm line and re-disassembles every byte
; sequence, so none of the three claims is merely asserted.
;
; THIS FILE IS GENERATED by that script's --emit; edit the script, not this.

;==========================================================================
; ALU r, (mem) and ALU (mem), r
;==========================================================================

; kn5000_v10_program.rom +0x142CE7 (rom 0xF42CE7) -- unidasm: add A,(XHL)
; CHECK: add a, (xhl)
; CHECK-ENC: encoding: [0x83,0x81]
; CHECK-INST: add a, (xhl)
add a, (xhl)

; kn5000_v10_program.rom +0x107422 (rom 0xF07422) -- unidasm: add (XWA),C
; CHECK: add (xwa), c
; CHECK-ENC: encoding: [0x80,0x8b]
; CHECK-INST: add (xwa), c
add (xwa), c

; kn5000_v10_program.rom +0x0F507A (rom 0xEF507A) -- unidasm: and A,(XDE)
; CHECK: and a, (xde)
; CHECK-ENC: encoding: [0x82,0xc1]
; CHECK-INST: and a, (xde)
and a, (xde)

; kn5000_v10_program.rom +0x1B59F2 (rom 0xFB59F2) -- unidasm: xor C,(XDE)
; CHECK: xor c, (xde)
; CHECK-ENC: encoding: [0x82,0xd3]
; CHECK-INST: xor c, (xde)
xor c, (xde)

; kn5000_v10_program.rom +0x1B6FF7 (rom 0xFB6FF7) -- unidasm: or C,(XWA)
; CHECK: or c, (xwa)
; CHECK-ENC: encoding: [0x80,0xe3]
; CHECK-INST: or c, (xwa)
or c, (xwa)

; kn5000_v10_program.rom +0x10EAAE (rom 0xF0EAAE) -- unidasm: cp A,(XBC)
; CHECK: cp a, (xbc)
; CHECK-ENC: encoding: [0x81,0xf1]
; CHECK-INST: cp a, (xbc)
cp a, (xbc)

; kn5000_v10_program.rom +0x0FAC16 (rom 0xEFAC16) -- unidasm: add A,(XIY+0x02)
; CHECK: add a, (xiy+2)
; CHECK-ENC: encoding: [0x8d,0x02,0x81]
; CHECK-INST: add a, (xiy+2)
add a, (xiy+2)

; kn5000_v10_program.rom +0x0F0046 (rom 0xEF0046) -- unidasm: add (XWA+0x88),A
; CHECK: add (xwa-120), a
; CHECK-ENC: encoding: [0x88,0x88,0x89]
; CHECK-INST: add (xwa-120), a
add (xwa-120), a

; kn5000_v10_program.rom +0x1E8DEF (rom 0xFE8DEF) -- unidasm: sub A,(XIZ+0x05)
; CHECK: sub a, (xiz+5)
; CHECK-ENC: encoding: [0x8e,0x05,0xa1]
; CHECK-INST: sub a, (xiz+5)
sub a, (xiz+5)

; kn5000_v10_program.rom +0x197766 (rom 0xF97766) -- unidasm: sub (XHL+0xde),A
; CHECK: sub (xhl-34), a
; CHECK-ENC: encoding: [0x8b,0xde,0xa9]
; CHECK-INST: sub (xhl-34), a
sub (xhl-34), a

; kn5000_v10_program.rom +0x0FC4FA (rom 0xEFC4FA) -- unidasm: and (XIX+0xcc),A
; CHECK: and (xix-52), a
; CHECK-ENC: encoding: [0x8c,0xcc,0xc9]
; CHECK-INST: and (xix-52), a
and (xix-52), a

; kn5000_v10_program.rom +0x106C2C (rom 0xF06C2C) -- unidasm: cp A,(XSP+0x10)
; CHECK: cp a, (xsp+16)
; CHECK-ENC: encoding: [0x8f,0x10,0xf1]
; CHECK-INST: cp a, (xsp+16)
cp a, (xsp+16)

; kn5000_v10_program.rom +0x12ACCA (rom 0xF2ACCA) -- unidasm: add BC,(XWA)
; CHECK: add bc, (xwa)
; CHECK-ENC: encoding: [0x90,0x81]
; CHECK-INST: add bc, (xwa)
add bc, (xwa)

; kn5000_v10_program.rom +0x15FE09 (rom 0xF5FE09) -- unidasm: adc WA,(XWA)
; CHECK: adc wa, (xwa)
; CHECK-ENC: encoding: [0x90,0x90]
; CHECK-INST: adc wa, (xwa)
adc wa, (xwa)

; kn5000_v10_program.rom +0x0F0060 (rom 0xEF0060) -- unidasm: adc IY,(XIY)
; CHECK: adc iy, (xiy)
; CHECK-ENC: encoding: [0x95,0x95]
; CHECK-INST: adc iy, (xiy)
adc iy, (xiy)

; kn5000_v10_program.rom +0x12B61F (rom 0xF2B61F) -- unidasm: sub WA,(XHL)
; CHECK: sub wa, (xhl)
; CHECK-ENC: encoding: [0x93,0xa0]
; CHECK-INST: sub wa, (xhl)
sub wa, (xhl)

; kn5000_v10_program.rom +0x1CCDA4 (rom 0xFCCDA4) -- unidasm: sbc (XWA),BC
; CHECK: sbc (xwa), bc
; CHECK-ENC: encoding: [0x90,0xb9]
; CHECK-INST: sbc (xwa), bc
sbc (xwa), bc

; kn5000_v10_program.rom +0x12EE56 (rom 0xF2EE56) -- unidasm: cp WA,(XHL)
; CHECK: cp wa, (xhl)
; CHECK-ENC: encoding: [0x93,0xf0]
; CHECK-INST: cp wa, (xhl)
cp wa, (xhl)

; kn5000_v10_program.rom +0x0F7634 (rom 0xEF7634) -- unidasm: cp (XIY),WA
; CHECK: cp (xiy), wa
; CHECK-ENC: encoding: [0x95,0xf8]
; CHECK-INST: cp (xiy), wa
cp (xiy), wa

; kn5000_v10_program.rom +0x0F4633 (rom 0xEF4633) -- unidasm: add WA,(XSP+0x1a)
; CHECK: add wa, (xsp+26)
; CHECK-ENC: encoding: [0x9f,0x1a,0x80]
; CHECK-INST: add wa, (xsp+26)
add wa, (xsp+26)

; kn5000_v10_program.rom +0x0F149B (rom 0xEF149B) -- unidasm: add (XHL+0xfe),WA
; CHECK: add (xhl-2), wa
; CHECK-ENC: encoding: [0x9b,0xfe,0x88]
; CHECK-INST: add (xhl-2), wa
add (xhl-2), wa

; kn5000_v10_program.rom +0x14A970 (rom 0xF4A970) -- unidasm: sbc DE,(XIY+0x28)
; CHECK: sbc de, (xiy+40)
; CHECK-ENC: encoding: [0x9d,0x28,0xb2]
; CHECK-INST: sbc de, (xiy+40)
sbc de, (xiy+40)

; kn5000_v10_program.rom +0x0F15C6 (rom 0xEF15C6) -- unidasm: cp WA,(XHL+0xf8)
; CHECK: cp wa, (xhl-8)
; CHECK-ENC: encoding: [0x9b,0xf8,0xf0]
; CHECK-INST: cp wa, (xhl-8)
cp wa, (xhl-8)

; kn5000_v10_program.rom +0x0F44F0 (rom 0xEF44F0) -- unidasm: cp (XSP+0x04),WA
; CHECK: cp (xsp+4), wa
; CHECK-ENC: encoding: [0x9f,0x04,0xf8]
; CHECK-INST: cp (xsp+4), wa
cp (xsp+4), wa

; kn5000_v10_program.rom +0x1DC42F (rom 0xFDC42F) -- unidasm: add XWA,(XDE)
; CHECK: add xwa, (xde)
; CHECK-ENC: encoding: [0xa2,0x80]
; CHECK-INST: add xwa, (xde)
add xwa, (xde)

; kn5000_v10_program.rom +0x119011 (rom 0xF19011) -- unidasm: add (XSP),XWA
; CHECK: add (xsp), xwa
; CHECK-ENC: encoding: [0xa7,0x88]
; CHECK-INST: add (xsp), xwa
add (xsp), xwa

; kn5000_v10_program.rom +0x14F63F (rom 0xF4F63F) -- unidasm: cp XWA,(XHL)
; CHECK: cp xwa, (xhl)
; CHECK-ENC: encoding: [0xa3,0xf0]
; CHECK-INST: cp xwa, (xhl)
cp xwa, (xhl)

; kn5000_v10_program.rom +0x179876 (rom 0xF79876) -- unidasm: cp (XIZ),XWA
; CHECK: cp (xiz), xwa
; CHECK-ENC: encoding: [0xa6,0xf8]
; CHECK-INST: cp (xiz), xwa
cp (xiz), xwa

; kn5000_v10_program.rom +0x0F4F23 (rom 0xEF4F23) -- unidasm: add XWA,(XSP+0x0c)
; CHECK: add xwa, (xsp+12)
; CHECK-ENC: encoding: [0xaf,0x0c,0x80]
; CHECK-INST: add xwa, (xsp+12)
add xwa, (xsp+12)

; kn5000_v10_program.rom +0x0F331E (rom 0xEF331E) -- unidasm: add (XSP+0x02),XWA
; CHECK: add (xsp+2), xwa
; CHECK-ENC: encoding: [0xaf,0x02,0x88]
; CHECK-INST: add (xsp+2), xwa
add (xsp+2), xwa

; kn5000_v10_program.rom +0x1789C9 (rom 0xF789C9) -- unidasm: sub XWA,(XSP+0x14)
; CHECK: sub xwa, (xsp+20)
; CHECK-ENC: encoding: [0xaf,0x14,0xa0]
; CHECK-INST: sub xwa, (xsp+20)
sub xwa, (xsp+20)

; kn5000_v10_program.rom +0x0F3A22 (rom 0xEF3A22) -- unidasm: cp XWA,(XSP+0x04)
; CHECK: cp xwa, (xsp+4)
; CHECK-ENC: encoding: [0xaf,0x04,0xf0]
; CHECK-INST: cp xwa, (xsp+4)
cp xwa, (xsp+4)

; kn5000_v10_program.rom +0x0F3A00 (rom 0xEF3A00) -- unidasm: cp (XSP+0x08),XWA
; CHECK: cp (xsp+8), xwa
; CHECK-ENC: encoding: [0xaf,0x08,0xf8]
; CHECK-INST: cp (xsp+8), xwa
cp (xsp+8), xwa
;==========================================================================
; ALU (mem), #imm
;==========================================================================

; kn5000_v10_program.rom +0x0F0D82 (rom 0xEF0D82) -- unidasm: cp (XHL),0x00
; CHECK: cp (xhl), 0
; CHECK-ENC: encoding: [0x83,0x3f,0x00]
; CHECK-INST: cp (xhl), 0
cp (xhl), 0

; kn5000_v10_program.rom +0x101895 (rom 0xF01895) -- unidasm: and (XHL),0x7f
; CHECK: andmi8 (xhl), 127
; CHECK-ENC: encoding: [0x83,0x3c,0x7f]
; CHECK-INST: andmi8 (xhl), 127
andmi8 (xhl), 127

; kn5000_v10_program.rom +0x136F06 (rom 0xF36F06) -- unidasm: add (XBC),0x0b
; CHECK: addmi8 (xbc), 11
; CHECK-ENC: encoding: [0x81,0x38,0x0b]
; CHECK-INST: addmi8 (xbc), 11
addmi8 (xbc), 11

; kn5000_v10_program.rom +0x0F1D39 (rom 0xEF1D39) -- unidasm: cp (XIX+0x09),0x03
; CHECK: cp (xix+9), 3
; CHECK-ENC: encoding: [0x8c,0x09,0x3f,0x03]
; CHECK-INST: cp (xix+9), 3
cp (xix+9), 3

; kn5000_v10_program.rom +0x116E76 (rom 0xF16E76) -- unidasm: sub (XSP+0x08),0x1e
; CHECK: submi8 (xsp+8), 30
; CHECK-ENC: encoding: [0x8f,0x08,0x3a,0x1e]
; CHECK-INST: submi8 (xsp+8), 30
submi8 (xsp+8), 30

; kn5000_v10_program.rom +0x0FC35E (rom 0xEFC35E) -- unidasm: cp (XIY),0x0000
; CHECK: cpw (xiy), 0
; CHECK-ENC: encoding: [0x95,0x3f,0x00,0x00]
; CHECK-INST: cpw (xiy), 0
cpw (xiy), 0

; kn5000_v10_program.rom +0x17C5F5 (rom 0xF7C5F5) -- unidasm: and (XWA),0xff7f
; CHECK: andmi16 (xwa), 65407
; CHECK-ENC: encoding: [0x90,0x3c,0x7f,0xff]
; CHECK-INST: andmi16 (xwa), 65407
andmi16 (xwa), 65407

; kn5000_v10_program.rom +0x0F2F48 (rom 0xEF2F48) -- unidasm: cp (XDE+0xfe),0x0000
; CHECK: cpw (xde-2), 0
; CHECK-ENC: encoding: [0x9a,0xfe,0x3f,0x00,0x00]
; CHECK-INST: cpw (xde-2), 0
cpw (xde-2), 0

; kn5000_v10_program.rom +0x0F44B8 (rom 0xEF44B8) -- unidasm: add (XSP+0x06),0x0012
; CHECK: addiw_da (xsp+6), 18
; CHECK-ENC: encoding: [0x9f,0x06,0x38,0x12,0x00]
; CHECK-INST: addiw_da (xsp+6), 18
addiw_da (xsp+6), 18
;==========================================================================
; PUSH (mem)
;==========================================================================

; kn5000_v10_program.rom +0x102435 (rom 0xF02435) -- unidasm: pushw (XDE)
; CHECK: pushm (xde)
; CHECK-ENC: encoding: [0x92,0x04]
; CHECK-INST: pushm (xde)
pushm (xde)

; kn5000_v10_program.rom +0x0F3C6E (rom 0xEF3C6E) -- unidasm: pushw (XSP+0x04)
; CHECK: pushm (xsp+4)
; CHECK-ENC: encoding: [0x9f,0x04,0x04]
; CHECK-INST: pushm (xsp+4)
pushm (xsp+4)
;==========================================================================
; Block transfers
;==========================================================================

; kn5000_v10_program.rom +0x11D280 (rom 0xF1D280) -- unidasm: ldi
; CHECK: ldi85
; CHECK-ENC: encoding: [0x85,0x10]
; CHECK-INST: ldi85
ldi85

; kn5000_v10_program.rom +0x0F0BC3 (rom 0xEF0BC3) -- unidasm: ldir
; CHECK: ldir83
; CHECK-ENC: encoding: [0x83,0x11]
; CHECK-INST: ldir83
ldir83

; kn5000_v10_program.rom +0x1016A5 (rom 0xF016A5) -- unidasm: lddr
; CHECK: lddr83
; CHECK-ENC: encoding: [0x83,0x13]
; CHECK-INST: lddr83
lddr83

; kn5000_v10_program.rom +0x1F28E0 (rom 0xFF28E0) -- unidasm: cpir
; CHECK: cpir83
; CHECK-ENC: encoding: [0x83,0x15]
; CHECK-INST: cpir83
cpir83

; kn5000_v10_program.rom +0x109966 (rom 0xF09966) -- unidasm: ldiw
; CHECK: ldiw
; CHECK-ENC: encoding: [0x95,0x10]
; CHECK-INST: ldiw
ldiw

; kn5000_v10_program.rom +0x0F0B64 (rom 0xEF0B64) -- unidasm: ldirw
; CHECK: ldirw93
; CHECK-ENC: encoding: [0x93,0x11]
; CHECK-INST: ldirw93
ldirw93
;==========================================================================
; EX / MUL / MULS / DIV / DIVS / shift on memory
;==========================================================================

; kn5000_v10_program.rom +0x1C49C3 (rom 0xFC49C3) -- unidasm: ex (XHL),A
; CHECK: ex (xhl), a
; CHECK-ENC: encoding: [0x83,0x31]
; CHECK-INST: ex (xhl), a
ex (xhl), a

; kn5000_v10_program.rom +0x19E150 (rom 0xF9E150) -- unidasm: muls XWA,(XIZ)
; CHECK: muls wa, (xiz)
; CHECK-ENC: encoding: [0x96,0x48]
; CHECK-INST: muls wa, (xiz)
muls wa, (xiz)

; kn5000_v10_program.rom +0x19D960 (rom 0xF9D960) -- unidasm: muls XBC,(XDE)
; CHECK: muls bc, (xde)
; CHECK-ENC: encoding: [0x92,0x49]
; CHECK-INST: muls bc, (xde)
muls bc, (xde)

; kn5000_v10_program.rom +0x1956E7 (rom 0xF956E7) -- unidasm: mul XWA,(XSP+0x0c)
; CHECK: mul wa, (xsp+12)
; CHECK-ENC: encoding: [0x9f,0x0c,0x40]
; CHECK-INST: mul wa, (xsp+12)
mul wa, (xsp+12)

; kn5000_v10_program.rom +0x1F26E0 (rom 0xFF26E0) -- unidasm: sllw (XWA)
; CHECK: sllw (xwa)
; CHECK-ENC: encoding: [0x90,0x7e]
; CHECK-INST: sllw (xwa)
sllw (xwa)

; kn5000_v10_program.rom +0x0F4E85 (rom 0xEF4E85) -- unidasm: srlw (XSP+0x04)
; CHECK: srlw (xsp+4)
; CHECK-ENC: encoding: [0x9f,0x04,0x7f]
; CHECK-INST: srlw (xsp+4)
srlw (xsp+4)
;==========================================================================
; Destination table bit operations
;==========================================================================

; kn5000_v10_program.rom +0x18A106 (rom 0xF8A106) -- unidasm: ldcf 7,(XWA)
; CHECK: ldcfm 7, (xwa)
; CHECK-ENC: encoding: [0xb0,0x9f]
; CHECK-INST: ldcfm 7, (xwa)
ldcfm 7, (xwa)

; kn5000_v10_program.rom +0x1D35A2 (rom 0xFD35A2) -- unidasm: stcf 7,(XDE)
; CHECK: stcfm 7, (xde)
; CHECK-ENC: encoding: [0xb2,0xa7]
; CHECK-INST: stcfm 7, (xde)
stcfm 7, (xde)

; kn5000_v10_program.rom +0x0F130E (rom 0xEF130E) -- unidasm: tset 6,(XIY)
; CHECK: tsetm 6, (xiy)
; CHECK-ENC: encoding: [0xb5,0xae]
; CHECK-INST: tsetm 6, (xiy)
tsetm 6, (xiy)

; kn5000_v10_program.rom +0x0F1EBF (rom 0xEF1EBF) -- unidasm: res 0,(XWA)
; CHECK: resm 0, (xwa)
; CHECK-ENC: encoding: [0xb0,0xb0]
; CHECK-INST: resm 0, (xwa)
resm 0, (xwa)

; kn5000_v10_program.rom +0x106926 (rom 0xF06926) -- unidasm: set 7,(XDE)
; CHECK: setm 7, (xde)
; CHECK-ENC: encoding: [0xb2,0xbf]
; CHECK-INST: setm 7, (xde)
setm 7, (xde)

; kn5000_v10_program.rom +0x0F139B (rom 0xEF139B) -- unidasm: bit 0,(XIY)
; CHECK: bitm 0, (xiy)
; CHECK-ENC: encoding: [0xb5,0xc8]
; CHECK-INST: bitm 0, (xiy)
bitm 0, (xiy)

; kn5000_v10_program.rom +0x1D31B9 (rom 0xFD31B9) -- unidasm: ldcf 0,(XDE+0x0b)
; CHECK: ldcfm 0, (xde+11)
; CHECK-ENC: encoding: [0xba,0x0b,0x98]
; CHECK-INST: ldcfm 0, (xde+11)
ldcfm 0, (xde+11)

; kn5000_v10_program.rom +0x14EBFF (rom 0xF4EBFF) -- unidasm: res 2,(XSP+0x04)
; CHECK: resm 2, (xsp+4)
; CHECK-ENC: encoding: [0xbf,0x04,0xb2]
; CHECK-INST: resm 2, (xsp+4)
resm 2, (xsp+4)

; kn5000_v10_program.rom +0x13B70A (rom 0xF3B70A) -- unidasm: set 7,(XSP+0x04)
; CHECK: setm 7, (xsp+4)
; CHECK-ENC: encoding: [0xbf,0x04,0xbf]
; CHECK-INST: setm 7, (xsp+4)
setm 7, (xsp+4)

; kn5000_v10_program.rom +0x1098D5 (rom 0xF098D5) -- unidasm: chg 2,(XHL+0x0e)
; CHECK: chgm 2, (xhl+14)
; CHECK-ENC: encoding: [0xbb,0x0e,0xc2]
; CHECK-INST: chgm 2, (xhl+14)
chgm 2, (xhl+14)

; kn5000_v10_program.rom +0x1391F9 (rom 0xF391F9) -- unidasm: bit 7,(XSP+0x00)
; CHECK: bitm 7, (xsp+256)
; CHECK-ENC: encoding: [0xbf,0x00,0xcf]
; CHECK-INST: bitm 7, (xsp+256)
bitm 7, (xsp+256)
;==========================================================================
; Destination table, no register in the opcode
;==========================================================================

; kn5000_v10_program.rom +0x106919 (rom 0xF06919) -- unidasm: stcf A,(XBC)
; CHECK: stcf a, (xbc)
; CHECK-ENC: encoding: [0xb1,0x2c]
; CHECK-INST: stcf a, (xbc)
stcf a, (xbc)
;==========================================================================
; RET cc
;==========================================================================

; kn5000_v10_program.rom +0x12B00E (rom 0xF2B00E) -- unidasm: ret GE
; CHECK: ret ge
; CHECK-ENC: encoding: [0xb0,0xf9]
; CHECK-INST: ret ge
ret ge

; kn5000_v9_program.rom +0x0FDB40 (rom 0xEFDB40) -- unidasm: ret GE
; CHECK: ret_cc_ri xiz, 9
; CHECK-ENC: encoding: [0xb6,0xf9]
; CHECK-INST: ret_cc_ri xiz, 9
ret_cc_ri xiz, 9
;==========================================================================
; JP cc, (mem) / CALL cc, (mem)
;==========================================================================

; no located ROM site -- encoding fixture, see the script -- unidasm: jp LT,XBC
; CHECK: jp lt, (xbc)
; CHECK-ENC: encoding: [0xb1,0xd1]
; CHECK-INST: jp lt, (xbc)
jp lt, (xbc)

; no located ROM site -- encoding fixture, see the script -- unidasm: jp LE,XBC+0x04
; CHECK: jp le, (xbc+4)
; CHECK-ENC: encoding: [0xb9,0x04,0xd2]
; CHECK-INST: jp le, (xbc+4)
jp le, (xbc+4)

; no located ROM site -- encoding fixture, see the script -- unidasm: call LT,XBC
; CHECK: call lt, (xbc)
; CHECK-ENC: encoding: [0xb1,0xe1]
; CHECK-INST: call lt, (xbc)
call lt, (xbc)
